name: Build Game Images

on:
  workflow_call:
    inputs:
      build-items:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-item: ${{ fromJson(inputs.build-items) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./game
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dontstarvetogether:${{ matrix.build-item.buildid }}
          build-args: |
            DST_BRANCH=${{ matrix.build-item.branch }}
            DST_BUILDID=${{ matrix.build-item.buildid }}
            DST_TIMEUPDATED=${{ matrix.build-item.timeupdated }}

      # Build and push to Private Docker Registry (110.40.166.27:5000)
      - name: Build and Push to Private Docker Registry
        env:
          PRIVATE_REGISTRY: 110.40.166.27:5000
        run: |
          docker build -t $PRIVATE_REGISTRY/dontstarvetogether:${{ matrix.build-item.buildid }} \
            --build-arg DST_BRANCH=${{ matrix.build-item.branch }} \
            --build-arg DST_BUILDID=${{ matrix.build-item.buildid }} \
            --build-arg DST_TIMEUPDATED=${{ matrix.build-item.timeupdated }} \
            ./game
          echo '{"insecure-registries":["110.40.166.27:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          docker push $PRIVATE_REGISTRY/dontstarvetogether:${{ matrix.build-item.buildid }}
